
package pl.mtjakobczyk.contracts.dictionaryfrontend;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "getStationFault", targetNamespace = "http://www.mtjakobczyk.pl/Schemas/DictionaryFrontend")
public class GetStationFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private pl.mtjakobczyk.schemas.dictionaryfrontend.GetStationFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetStationFault(String message, pl.mtjakobczyk.schemas.dictionaryfrontend.GetStationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetStationFault(String message, pl.mtjakobczyk.schemas.dictionaryfrontend.GetStationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: pl.mtjakobczyk.schemas.dictionaryfrontend.GetStationFault
     */
    public pl.mtjakobczyk.schemas.dictionaryfrontend.GetStationFault getFaultInfo() {
        return faultInfo;
    }

}
