
package pl.mtjakobczyk.contracts.freightfrontend;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FreightService", targetNamespace = "http://www.mtjakobczyk.pl/contracts/FreightFrontend/", wsdlLocation = "file:/C:/git/github/FreightUtility/resources/contracts/FreightFrontend.wrapped.wsdl")
public class FreightService
    extends Service
{

    private final static URL FREIGHTSERVICE_WSDL_LOCATION;
    private final static WebServiceException FREIGHTSERVICE_EXCEPTION;
    private final static QName FREIGHTSERVICE_QNAME = new QName("http://www.mtjakobczyk.pl/contracts/FreightFrontend/", "FreightService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/git/github/FreightUtility/resources/contracts/FreightFrontend.wrapped.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FREIGHTSERVICE_WSDL_LOCATION = url;
        FREIGHTSERVICE_EXCEPTION = e;
    }

    public FreightService() {
        super(__getWsdlLocation(), FREIGHTSERVICE_QNAME);
    }

    public FreightService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FREIGHTSERVICE_QNAME, features);
    }

    public FreightService(URL wsdlLocation) {
        super(wsdlLocation, FREIGHTSERVICE_QNAME);
    }

    public FreightService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FREIGHTSERVICE_QNAME, features);
    }

    public FreightService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FreightService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IFreight
     */
    @WebEndpoint(name = "FreightServicePort")
    public IFreight getFreightServicePort() {
        return super.getPort(new QName("http://www.mtjakobczyk.pl/contracts/FreightFrontend/", "FreightServicePort"), IFreight.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFreight
     */
    @WebEndpoint(name = "FreightServicePort")
    public IFreight getFreightServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.mtjakobczyk.pl/contracts/FreightFrontend/", "FreightServicePort"), IFreight.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FREIGHTSERVICE_EXCEPTION!= null) {
            throw FREIGHTSERVICE_EXCEPTION;
        }
        return FREIGHTSERVICE_WSDL_LOCATION;
    }

}
