
package pl.mtjakobczyk.contracts.freightfrontend;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.tibco.schemas.handlingschema.Shipment;
import com.tibco.schemas.handlingschema.Shipments;
import pl.mtjakobczyk.schemas.freightfrontend.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IFreight", targetNamespace = "http://www.mtjakobczyk.pl/contracts/FreightFrontend/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IFreight {


    /**
     * 
     * @param searchedAWB
     * @param shipments
     */
    @WebMethod(action = "getShipment")
    @RequestWrapper(localName = "getShipment", targetNamespace = "http://www.mtjakobczyk.pl/Schemas/FreightFrontend", className = "pl.mtjakobczyk.schemas.freightfrontend.GetShipment")
    @ResponseWrapper(localName = "getShipmentResponse", targetNamespace = "http://www.mtjakobczyk.pl/Schemas/FreightFrontend", className = "pl.mtjakobczyk.schemas.freightfrontend.GetShipmentResponse")
    public void getShipment(
        @WebParam(name = "searchedAWB", targetNamespace = "http://www.mtjakobczyk.pl/Schemas/FreightFrontend", mode = WebParam.Mode.INOUT)
        Holder<String> searchedAWB,
        @WebParam(name = "shipments", targetNamespace = "http://www.tibco.com/schemas/HandlingSchema", mode = WebParam.Mode.OUT)
        Holder<Shipments> shipments);

    /**
     * 
     * @param shipment
     * @throws NewShipmentFault
     */
    @WebMethod(action = "newShipment")
    @RequestWrapper(localName = "newShipment", targetNamespace = "http://www.mtjakobczyk.pl/Schemas/FreightFrontend", className = "pl.mtjakobczyk.schemas.freightfrontend.NewShipment")
    @ResponseWrapper(localName = "newShipmentResponse", targetNamespace = "http://www.mtjakobczyk.pl/Schemas/FreightFrontend", className = "pl.mtjakobczyk.schemas.freightfrontend.NewShipmentResponse")
    public void newShipment(
        @WebParam(name = "shipment", targetNamespace = "http://www.tibco.com/schemas/HandlingSchema", mode = WebParam.Mode.INOUT)
        Holder<Shipment> shipment)
        throws NewShipmentFault
    ;

}
