
package pl.mtjakobczyk.contracts.freightfrontend;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "newShipmentFault", targetNamespace = "http://www.mtjakobczyk.pl/Schemas/FreightFrontend")
public class NewShipmentFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private pl.mtjakobczyk.schemas.freightfrontend.NewShipmentFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NewShipmentFault(String message, pl.mtjakobczyk.schemas.freightfrontend.NewShipmentFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NewShipmentFault(String message, pl.mtjakobczyk.schemas.freightfrontend.NewShipmentFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: pl.mtjakobczyk.schemas.freightfrontend.NewShipmentFault
     */
    public pl.mtjakobczyk.schemas.freightfrontend.NewShipmentFault getFaultInfo() {
        return faultInfo;
    }

}
